export const snooper = {
    message: `..............................
..............................
....                      ....
....      ..........\`     ....
....      ..........\`     ....
....           \`....\`     ....
....           \`....\`     ....
....           \`....\`     ....
....           \`....\`     ....
....      .\`   \`....\`     ....
....    \`...........\`     ....
....     \`.........\`      ....
....        \`\`\`\`\`         ....
..............................
..............................


Looking for something? You can use the blog to search for specific topics, or contact me directly at josh@jargonify.com

This site was developed with mobile in mind. It uses Angular, is responsive, PWA-enabled, lazy-loaded, and has a minimal footprint.

It's not perfect - see planned improvements here:
https://github.com/joshhills/jargonify-site/projects/1

~ Josh`,
    css: 'color: #ffa351;'
};
